amper.id = 1
amper.port = 7777


amper.rootDirectory = /Users/grigornazaryan/Documents/Workspace/amper/luncher/data
amper.adobeLicenseKey = 806291ab74be42e49ebb59a099496bec
resources = 192.168.2.11:8080
uinodes = http://dev.amper.cloud:3000/
mail.interface = gmail
gmail.from = smtp.amper.cloud@gmail.com
mail.smtp.host = 192.168.2.11
mail.pop3.host = 192.168.2.11
mail.smtp.port = 25
mail.smtp.from = admin@mail.amp-er.com
mail.smtp.username = admin@mail.amp-er.com
mail.smtp.password = amper123
amper.imap = {"domains":[{"id":"MTY5NDU0ODM5ODE2Mg==","name":"Google","domain":"gmail.com","serverName":"imap.gmail.com","port":993,"auth":""},{"id":"MTY5NDU0ODQ2MDYxOA==","name":"Hotmail","domain":"hotmail.com","serverName":"outlook.office365.com","port":993,"auth":""}]}
amper.smtp = {"domains":[{"id":"MTY5NTc1MDYxNDE1Mw==","name":"Hotmail","domain":"hotmail.com","serverName":"smtp.office365.com","port":587,"auth":"Login auth"},{"id":"MTY5NTc1NzE2ODIxMA==","name":"Gmail","domain":"gmail.com","serverName":"smtp.gmail.com","port":587,"auth":"Plain auth"}]}
