! The file holds properties for database communication configuration

user=root
password=amper123
host=127.0.0.1
port=3306
dbname=amper

# Database connection configuration
#connMaxLifeTime=0
maxIdleConns=5
maxOpenConns=3